barbershop/urls.py
from django.contrib import admin
from core.views import *
from django.conf import settings
from django.conf.urls.static import static
from django.urls import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingView.as_view(), name='landing'),
    path('thanks/', ThanksView.as_view(), name='thanks'),
    path('orders/', OrdersListView.as_view(), name='orders_list'),
    path('order/<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
    path('review/create/', ReviewCreateView.as_view(), name='create_review'),
    path('order/create/', OrderCreateView.as_view(), name='create_order'),
    path('users/', include('users.urls'))

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('register/',  UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('profile/', UserProfileDetailView.as_view(), name='profile_detail'),
    path('profile/edit/', UserProfileUpdateView.as_view(), name='profile_edit'),
    path('password_change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('password-reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatars/', blank=True, null=True)
    birth_date = models.DateField(null=True, blank=True)
    telegram_id = models.CharField(max_length=100, blank=True, null=True)
    github_id = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return f'Профиль {self.user.username}'

@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    
    profile, created = Profile.objects.get_or_create(user=instance)

    if created:
        pass

users/forms.py
from django import forms
from django.contrib.auth.forms import (
    UserCreationForm,
    AuthenticationForm,
)
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import PasswordChangeForm, PasswordResetForm, SetPasswordForm
from .models import Profile



class UserRegisterForm(UserCreationForm):

    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'})
    )
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].widget.attrs.update({
                'class': 'form-control',
                'placeholder': self.fields[fieldname].label
            })
            
    def clean_email(self):

        email = self.cleaned_data.get('email')

        if User.objects.filter(email=email).exists():
            raise ValidationError("Такой email уже заренистрирован.")
        
        return email


class UserLoginForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Имя пользователя'
        })
        
        self.fields['password'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Пароль'
        })


class UserProfileUpdateForm(forms.ModelForm):

    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))

    class Meta:

        model = Profile
        fields = ['avatar', 'birth_date', 'telegram_id', 'github_id']
        widgets = {
            'birth_date': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'telegram_id': forms.TextInput(attrs={'class': 'form-control'}),
            'github_id': forms.TextInput(attrs={'class': 'form-control'}),
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].initial = self.instance.user.username
        self.fields['email'].initial = self.instance.user.email
    
    def save(self, commit=True):

        profile = super().save(commit=False)
        profile.user.username = self.cleaned_data['username']
        profile.user.email = self.cleaned_data['email']

        if commit:
            profile.user.save()
            profile.save()

        return profile


class UserPasswordChangeForm(PasswordChangeForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['old_password'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введите текущий пароль:'
        })

        self.fields['new_password1'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введите новый пароль:'
        })

        self.fields['new_password2'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Повторите новый пароль:'
        })


class CustomPasswordResetForm(PasswordResetForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['email'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Email'
        })


class CustomSetPasswordForm(SetPasswordForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['new_password1'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Новый пароль'
        })
        
        self.fields['new_password2'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Подтверждение нового пароля'
        })

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import *
from django.contrib.auth import login
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.contrib import messages
from .models import Profile
from .forms import ( 
    UserRegisterForm, 
    UserLoginForm, 
    CustomPasswordResetForm, 
    CustomSetPasswordForm,
    UserPasswordChangeForm,
    UserProfileUpdateForm,
)
from django.views.generic import (
    CreateView,  
    DetailView, 
    UpdateView,
)
from django.contrib.auth.views import (
    PasswordChangeView,  
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView, 
    PasswordResetCompleteView,
)



class UserLoginView(LoginView):

    form_class = UserLoginForm
    template_name = 'users/login.html'
    redirect_authenticated_user = True
    
    def get_success_url(self):
        return reverse_lazy('landing')


class UserLogoutView(LogoutView):

    template_name = 'users/logout.html'
    next_page = reverse_lazy('logout')

    def dispatch(self, request, *args, **kwargs):
        messages.success(request, "Вы вышли, надеюсь вас не собьёт автобус")
        return super().dispatch(request, *args, **kwargs)


class UserRegisterView(CreateView):

    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('login')
    
    def form_valid(self, form):

        response = super().form_valid(form)
        user = self.object
        login(self.request, user)

        return response
    
    def dispatch(self, request, *args, **kwargs):

        if request.user.is_authenticated:
            return redirect(self.success_url)
        
        return super().dispatch(request, *args, **kwargs)
    
    def form_valid(self, form):

        response = super().form_valid(form)
        user = self.object
        login(self.request, user)
        messages.success(self.request, "Вы успешно зарегистрировались! Добро пожаловать в клуб приятель!")
        
        return response
    

class CustomPasswordResetView(PasswordResetView):

    form_class = CustomPasswordResetForm
    template_name = 'users/password_reset_form.html'
    email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('password_reset_done')


class CustomPasswordResetConfirmView(PasswordResetConfirmView):

    form_class = CustomSetPasswordForm
    template_name = 'users/password_reset_confirm.html'
    success_url = reverse_lazy('password_reset_complete')


class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'users/password_reset_complete.html'


class CustomPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'users/password_reset_done.html'


class UserProfileDetailView(LoginRequiredMixin, DetailView):

    model = Profile
    template_name = 'users/profile_detail.html'
    context_object_name = 'profile'
    
    def get_object(self):
        return self.request.user.profile


class UserProfileUpdateView(LoginRequiredMixin, UpdateView):

    model = Profile
    form_class = UserProfileUpdateForm
    template_name = 'users/profile_update_form.html'
    success_url = reverse_lazy('profile_detail')
    
    def get_object(self):
        return self.request.user.profile
    
    def form_valid(self, form):
        messages.success(self.request, "Профиль успешно обновлен!")
        return super().form_valid(form)
    

class UserPasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    
    form_class = UserPasswordChangeForm
    template_name = 'users/password_change_form.html'
    success_url = reverse_lazy('profile_detail')

    def form_valid(self, form):
        messages.success(self.request, "Пароль успешно изменен!")
        return super().form_valid(form)

users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">

                <div class="card-header">
                    <h3>Вход</h3>
                </div>
                
                <div class="card-body">                    
                    <form method="post">

                        {% csrf_token %}
                        {{ form.as_p }}
                        
                        <button type="submit" class="btn btn-primary">Ворваться</button>
                    </form>

                    <div class="mt-3 text-center">
                        <a href="{% url 'password_reset' %}" class="text-decoration-none">
                            Альцгеймер? (для тех кто забыл пароль)
                        </a>
                    </div>

                </div>

            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/logout.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">

                <div class="card-header bg-dark text-white">
                    <h1>Зачем???</h1>
                </div>

                <div class="card-body text-center">

                    <p>Вы покинули нас...</p>

                    <div class="mt-3">

                        <a href="{% url 'landing' %}" class="btn btn-dark">
                            <i class="bi bi-house"></i> На начальную страницу
                        </a>

                    </div>

                </div>

            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/password_change_form.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">

                <div class="card-header bg-primary text-white">
                    <h4>Смена пароля</h4>
                </div>
                
                <div class="card-body">
                    {% if form.errors %}
                        <div class="alert alert-danger">
                            <strong>Ошибка!</strong> Пожалуйста, исправьте следующие ошибки:
                            <ul>
                                {% for field, errors in form.errors.items %}
                                    {% for error in errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                    
                    <form method="post">
                        {% csrf_token %}
                        
                        <div class="mb-3">
                            <label for="{{ form.old_password.id_for_label }}" class="form-label">Текущий пароль</label>
                            {{ form.old_password }}
                            {% if form.old_password.errors %}
                                <div class="text-danger">
                                    {% for error in form.old_password.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                        
                        <div class="mb-3">
                            <label for="{{ form.new_password1.id_for_label }}" class="form-label">Новый пароль</label>
                            {{ form.new_password1 }}
                            {% if form.new_password1.errors %}
                                <div class="text-danger">
                                    {% for error in form.new_password1.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                        
                        <div class="mb-3">
                            <label for="{{ form.new_password2.id_for_label }}" class="form-label">Подтверждение нового пароля</label>
                            {{ form.new_password2 }}
                            {% if form.new_password2.errors %}
                                <div class="text-danger">
                                    {% for error in form.new_password2.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                        
                        <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-primary">Изменить пароль</button>
                            <a href="{% url 'profile_detail' %}" class="btn btn-secondary">Отмена</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">

                <div class="card-header bg-success text-white">
                    <h4>Пароль успешно изменен!</h4>
                </div>

                <div class="card-body">
                    <p>Ваш пароль был успешно изменен. Теперь вы можете войти с новым паролем.</p>
                    <a href="{% url 'login' %}" class="btn btn-primary">Войти в систему</a>
                </div>
                
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">

                <div class="card-header bg-warning">
                    <h4>Установка нового пароля</h4>
                </div>

                <div class="card-body">
                    {% if validlink %}

                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Сохранить пароль</button>
                        </form>

                    {% else %}
                        <p>Ссылка недействительна. Запросите новую.</p>
                        <a href="{% url 'password_reset' %}" class="btn btn-primary">Получить новую ссылку</a>
                    {% endif %}
                    
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">  
            <div class="card">

                <div class="card-header bg-success text-white">
                    <h4>Письмо отправлено</h4>
                </div>

                <div class="card-body">
                    <p>Письмо для востановления пароля отправлено на вашу почту.</p>
                    <a href="{% url 'landing' %}" class="btn btn-secondary">На начальную страницу</a>
                </div>

            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}
{% autoescape off %}
{% blocktrans %}Вы получили это письмо, потому что у вас альцгеймер {{ site_name }}.{% endblocktrans %}

{% trans "Перейдите по ссылке и установите новый пароль:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Ваше имя пользователя, на случай если у вас альцгеймер:" %} {{ user.get_username }}

{% trans "Не топтать тут мне!" %}

{% blocktrans %}Команда {{ site_name }}{% endblocktrans %}
{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">

                <div class="card-header bg-primary text-white">
                    <h4>Восстановление пароля</h4>
                </div>

                <div class="card-body">
                    <p>Введите email, указанный при регистрации:</p>

                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary mt-3">Отправить</button>
                    </form>

                </div>

            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/profile_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-5">
    <div class="row">
        <div class="col-md-4">
            <div class="card">

                <div class="card-header bg-primary text-white">
                    <h4>Профиль пользователя</h4>
                </div>

                <div class="card-body text-center">
                    
                    {% if profile.avatar %}
                        <img src="{{ profile.avatar.url }}" alt="Аватар" class="rounded-circle mb-3" width="150" height="150">
                    {% else %}
                        <div class="bg-secondary rounded-circle d-flex align-items-center justify-content-center mb-3" style="width: 150px; height: 150px;">
                            <span class="text-white">Нет аватара</span>
                        </div>
                    {% endif %}
                    
                    <h5>{{ profile.user.username }}</h5>
                    <p class="text-muted">{{ profile.user.email }}</p>
                    <a href="{% url 'profile_edit' %}" class="btn btn-outline-primary btn-sm">Редактировать</a>
                </div>

            </div>
        </div>
        
        <div class="col-md-8">
            <div class="card mb-4">

                <div class="card-header">Информация</div>
                <div class="card-body">

                    <div class="row">

                        <div class="col-sm-3">
                            <p class="mb-0">Дата рождения</p>
                        </div>

                        <div class="col-sm-9">
                            <p class="text-muted mb-0">{{ profile.birth_date|default:"Не указана" }}</p>
                        </div>

                    </div>

                    <hr>
                    <div class="row">

                        <div class="col-sm-3">
                            <p class="mb-0">Telegram</p>
                        </div>

                        <div class="col-sm-9">
                            <p class="text-muted mb-0">{{ profile.telegram_id|default:"Не указан" }}</p>
                        </div>

                    </div>
                    <hr>

                    <div class="row">

                        <div class="col-sm-3">
                            <p class="mb-0">GitHub</p>
                        </div>

                        <div class="col-sm-9">
                            <p class="text-muted mb-0">{{ profile.github_id|default:"Не указан" }}</p>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/profile_update_form.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">

                <div class="card-header bg-primary text-white">
                    <h4>Редактирование профиля</h4>
                </div>

                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">

                        {% csrf_token %}

                        <div class="mb-3">
                            <label for="id_username" class="form-label">Имя пользователя</label>
                            {{ form.username }}
                        </div>

                        <div class="mb-3">
                            <label for="id_email" class="form-label">Email</label>
                            {{ form.email }}
                        </div>

                        <div class="mb-3">
                            <label for="id_avatar" class="form-label">Аватар</label>
                            {{ form.avatar }}
                        </div>

                        <div class="mb-3">
                            <label for="id_birth_date" class="form-label">Дата рождения</label>
                            {{ form.birth_date }}
                        </div>

                        <div class="mb-3">
                            <label for="id_telegram_id" class="form-label">Telegram ID</label>
                            {{ form.telegram_id }}
                        </div>

                        <div class="mb-3">
                            <label for="id_github_id" class="form-label">GitHub ID</label>
                            {{ form.github_id }}
                        </div>

                        <button type="submit" class="btn btn-primary">Сохранить изменения</button>
                        <a href="{% url 'profile_detail' %}" class="btn btn-secondary">Отмена</a>
                    
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">

                <div class="card-header">
                    <h3>Регистрация</h3>
                </div>
                
                <div class="card-body">

                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}

                        <button type="submit" class="btn btn-primary">Стать частью корабля</button>

                    </form>

                    <div class="mt-3 text-center">
                        <a href="{% url 'login' %}" class="text-decoration-none">
                            Уже есть аккаунт?
                        </a>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}